### ISSUE TITLE
Add test that runs an atomicapp 

### ISSUE THREAD

**Issue by dustymabe** [kushaldas/tunirtests#16]
This would catch bugs like: 

https://bugzilla.redhat.com/show_bug.cgi?id=1278984

**Comment by kushaldas** [comment]
I have added that docker command directly for now as a test in 1acb46935a635fddc6cccfd4922b8401f885a3fd

**Comment by dustymabe** [comment]
looks good.. added one comment to commit. check it out

**Comment by kushaldas** [comment]
Closing this ticket. Fixed in master.
