### ISSUE TITLE
Add test for basic filesystem permission sanity checks

### ISSUE THREAD

**Issue by dustymabe** [kushaldas/tunirtests#17]
We had a bug where /tmp was effectively 755 permissions:

https://bugzilla.redhat.com/show_bug.cgi?id=1276775

We need to somehow test for something like this... One option may be to run an rpm -q on the filesystem rpm and determine what the permissions should be and query based on that. Either way more checking here would be better than none.

**Comment by kushaldas** [comment]
Commit fb1dd6a2f9b269406745a3589e1f0f9e3a61ca71 and 818273cebb6f250e84118e5217caa4f88385a7e4 contains tests related to this issue. Please let us know if you want to more add more tests into this.

**Comment by dustymabe** [comment]
`stat -c '%a' /tmp` This is not good enough because it doesn't dereference the symlink if it is a link. You need `stat -L -c '%a' /tmp`. This test should be run on all hosts and not just on atomic. This test should check and match the string `1777`, not `777`

You need to make sure you aren't root when you check if `/tmp/` is writeable. This test should run on all hosts, not just atomic.

**Comment by kushaldas** [comment]
Closing this ticket. Fixed in master.

**Comment by kushaldas** [comment]
The actual text needs to checked is something like: "Server:\n Version"
