### ISSUE TITLE
make sure journal gets written to disk

### ISSUE THREAD

**Issue by dustymabe** [kushaldas/tunirtests#28]
Once these bugs get fixed let's test for it.

https://bugzilla.redhat.com/show_bug.cgi?id=1289902
https://bugzilla.redhat.com/show_bug.cgi?id=1265295

**Comment by nzwulfin** [comment]
This was closed by #30 @kushaldas

**Comment by kushaldas** [comment]
Current F23 system returns two PID while searching for journal.

$ pgrep journal
537
956

$ ps aux | grep journal
root       537  0.0  0.6  45640  6272 ?        Ss   08:59   0:00 /usr/lib/systemd/systemd-journald
root       953  0.0  0.2  13992  3036 ?        Ss   09:00   0:00 /bin/sh -c /usr/bin/docker daemon            $OPTIONS            $DOCKER_STORAGE_OPTIONS            $DOCKER_NETWORK_OPTIONS            $INSECURE_REGISTRY            2>&1 | /usr/bin/forward-journald -tag docker
root       955  0.0  3.2 478160 32664 ?        Sl   09:00   0:00 /usr/bin/docker daemon --selinux-enabled --log-driver=journald --storage-driver devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/atomicos-docker--pool --storage-opt dm.use_deferred_removal=true --storage-opt dm.use_deferred_deletion=true
root       956  0.0  0.3  36876  3836 ?        Sl   09:00   0:00 /usr/bin/forward-journald -tag docker
root      1154  0.0  0.2  11360  2244 pts/0    S+   09:03   0:00 grep --color=auto journal

This is causing the current test to fail.

**Comment by kushaldas** [comment]
We can use pidof command instead.

-bash-4.3# which pidof
/usr/sbin/pidof
-bash-4.3# sudo rpm -qf /usr/sbin/pidof
procps-ng-3.3.10-9.fc23.x86_64
-bash-4.3# pidof systemd-journald
537

**Comment by kushaldas** [comment]
Even better command (thanks to mattdm)

systemctl show systemd-journald.service -p MainPID

**Comment by trishnaguha** [comment]
We can see https://apps.fedoraproject.org/autocloud/jobs/90/output#290 and https://apps.fedoraproject.org/autocloud/jobs/86/output#294 are failing for journald test.

As per @dustymabe fedora23 and fedora24 atomic images are writing journallogs to /run instead of /var on first boot.
We should have check for the location also in journald test.
Also I just checked `user-*.journal` for atomic images is not getting written on first boot. Is that expected?

**Comment by dustymabe** [comment]
hey @trishnaguha @kushaldas do we know why the previous version of the test is giving us false "success" in some cases? This should be failing on all of the atomic cloud images, not just the vagrant ones.

https://apps.fedoraproject.org/autocloud/jobs/32?family=a&arch=&image_type=&status=

**Comment by trishnaguha** [comment]
@dustymabe From here https://apps.fedoraproject.org/autocloud/jobs/90/output#295 and https://apps.fedoraproject.org/autocloud/jobs/86/output#300 I understand that `user-*.journal` is not getting written(even after the first reboot) but `system.journal` does, whereas the other atomic images are not having this issue. 

In other atomic images we see both `user-*.journal` and `system.journal` are getting written at least after first reboot. 
cc @kushaldas 

The current test I just added need to be tested on First Boot(Not after reboot) to make sure both `system.journal` and `user-*.journal` are getting written on the very first boot.
