### ISSUE TITLE
Decide which service to manipulate based Fedora version

### ISSUE THREAD

**Issue by kushaldas** [kushaldas/tunirtests#55]
https://apps.fedoraproject.org/autocloud/jobs/946/output#297 we need to decide which service to stop/disable based on Fedora version.

**Comment by trishnaguha** [comment]
We can run cron service test for fedora <25 and chrony srevice test for fedora>=25.

For that We will need to add fedora release version check in https://github.com/kushaldas/tunirtests/blob/master/testutils.py and write test in https://github.com/kushaldas/tunirtests/blob/master/cloudservice.py accordingly.

**Comment by kushaldas** [comment]
Yes, this is what I have started writing last night.
