### ISSUE TITLE
Test to run a container with root bind mounted

### ISSUE THREAD

**Issue by kushaldas** [kushaldas/tunirtests#8]
-bash-4.3# docker run -it --rm -v /:/host busybox
Error response from daemon: Relabeling of / is not allowed

**Comment by d1ndra** [comment]
@kushaldas I would like to work on this. Could you tell me where to start?

**Comment by kushaldas** [comment]
@d1ndra https://github.com/kushaldas/tunirtests/blob/master/atomictests.py add the test here.
